In [2]:
import pandas as pd

In [4]:
file_path = './results/clustered_data.csv'

df = pd.read_csv(file_path)

df

,dog,cat,rabbit,deer,panda,koala,otter,hedgehog,squirrel,dolphin,...,button,whistle,marble,wagon,storybook,candle,clover,bubble,cookie,segment
0,72,0D45,NaN,2.70,0,T0,B9DE,28.2,0,1,...,-5,8,0,-0.96,-73,B4,0.61,0,C16,7
1,44,C09E,NaN,4.54,0,T2,B9DE,38.8,0,1,...,28,14,0,-0.81,-86,B4,0.11,0,C16,0
2,50,1520,NaN,3.12,-1,T1,B9DE,41.0,0,1,...,-31,8,0,-0.64,32,B1,0.07,0,C8,3
3,36,D668,NaN,4.37,0,T1,027A,41.0,1,1,...,37,11,0,-0.94,-76,B2,0.07,0,C9,0
4,31,A2FB,47.0,4.36,-2,T3,027A,39.0,0,1,...,-25,2,0,-0.69,-66,B4,0.44,0,C18,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,48,5A6C,NaN,3.39,-1,T0,B9DE,34.4,0,1,...,-16,1,0,-0.77,59,B2,0.48,0,C12,6
1996,53,A639,35.0,2.64,-3,T0,B9DE,41.0,1,1,...,28,1,0,-0.92,80,B4,0.17,1,C17,7
1997,28,027A,NaN,4.52,-1,T3,B9DE,37.4,1,1,...,5,1,0,-0.72,-81,B0,1.45,0,C2,1
1998,41,C09E,NaN,2.42,-4,T0,B9DE,36.8,1,1,...,-3,13,0,-0.83,79,B4,1.21,1,C17,7
1999,21,ACAB,NaN,4.64,0,T3,B9DE,34.8,0,1,...,14,2,0,-0.79,-79,B0,0.54,1,C2,1

In [21]:
df.isnull().sum() > 0

dog          False
cat          False
rabbit        True
deer         False
panda        False
             ...
storybook    False
candle       False
clover       False
bubble       False
cookie       False
Length: 80, dtype: bool

In [22]:
cols_na = df.columns[df.isnull().sum() > 0].tolist() # 결측치 열 추출
cols_na

['rabbit', 'cow', 'loon', 'cloud']

In [36]:
from denseclus import DenseClus
from denseclus.utils import make_dataframe

df = make_dataframe() # 단순한 데이터 프레임
df

,num_0,num_1,num_2,num_3,num_4,num_5,cat_0,cat_1,cat_2,cat_3
0,-0.079539,-1.112247,1.330465,0.619461,1.439154,1.017511,MH,MH,L,HL
1,0.603084,-1.533468,1.094063,0.979311,2.188478,1.255139,L,H,M,HL
2,0.662771,0.427754,1.344634,-0.293283,0.158497,-0.511817,H,H,M,MH
3,-0.594482,0.822316,-0.161324,-0.277995,-0.356401,-0.998711,H,H,L,M
4,0.769634,-0.647046,0.977899,0.078718,0.658668,1.286979,MH,MH,HL,HL
...,...,...,...,...,...,...,...,...,...,...
995,-1.320274,-0.156966,-0.582557,0.282833,-0.471954,-1.028828,MH,L,L,M
996,0.150103,1.341845,-1.493453,0.431241,-1.098594,-0.428811,MH,MH,MH,L
997,-1.532087,-0.525841,-0.687205,0.825706,0.428639,-0.870188,M,H,L,H
998,0.191477,0.432728,-0.245239,-1.094670,-0.819430,0.192776,M,HL,M,M
999,-0.009676,1.399951,0.700014,1.637921,0.722500,-0.511025,L,H,HL,M

In [34]:
clf = DenseClus()

clf.fit(df)

/home/station_05/anaconda3/envs/torch_ev/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/station_05/anaconda3/envs/torch_ev/lib/python3.11/site-packages/umap/umap_.py:1887: UserWarning: gradient function is not yet implemented for hamming distance metric; inverse_transform will be unavailable
  warn(
/home/station_05/anaconda3/envs/torch_ev/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/station_05/anaconda3/envs/torch_ev/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/station_05/anaconda3/envs/torch_ev/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [39]:
scores = clf.evaluate()

Coverage 0.691
Calinski-Harabasz Score: 658.1399420546541

In [41]:
print(scores[0:10])

[ 0  0  2 -1  0 -1 -1  2  2  1]

In [42]:
labels = clf.score()

TypeError: ClassifierMixin.score() missing 2 required positional arguments: 'X' and 'y'